<!DOCTYPE html><html lang="zh-CN"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>错误的传播和拦截 | Node.js API 文档</title>
  
  

    <link href="../../api/static/inject.css" rel="stylesheet"><link rel="icon" sizes="32x32" type="image/png" href="../../api/static/favicon.png"></head>

<body class="alt apidoc" id="page_api_item">
  <div id="api-section-errors">
    <div id="content" class="clearfix">

      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>错误的传播和拦截</h1>
          <div id="gtoc">
            <ul>
              <li>v16.16.0</li>
              <li>
                <a href="../errors.html#errors_error_propagation_and_interception" name="toc">返回上层文档</a>
              </li>

              <li class="picker-header">
    <a href="#">
        <span class="collapsed-arrow">►</span><span class="expanded-arrow">▼</span>
        其他版本
      </a>
    <div class="picker"><ol id="alt-docs">
    <li><a href="../../api/errors/error_propagation_and_interception.html">18.6.0</a></li><li><a href="">16.16.0</a></li><li><a href="../../api-v14/errors/error_propagation_and_interception.html">14.20.0</a></li>
</ol></div>
  </li>

              <li>
                <a href="http://api.nodejs.cn/" class="link-to-search">搜索</a>
              </li>
              <li>
                
                
              </li>

              <!-- <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/errors/#error-propagation-and-interception.md" rel="nofollow">提交修改</a>
              </li> -->
              <!-- <li>
                <a href="/gzh/">公众号</a>
              </li> -->
              <!-- <li class="biz_wrap" data-biz="api_item_nav">
                <a target="_blank" class="biz_title biz_link"></a>
              </li> -->
            </ul>
          </div>
          <hr>
        </header>

        <div id="apicontent">
          <div id="content_left"><p>Node.js 支持多种机制来传播和处理应用程序运行时发生的错误。
如何报告和处理这些错误完全取决于 <code>Error</code> 的类型和调用的 API 的风格。</p><p class="">所有的 JavaScript 错误都作为异常处理，使用标准的 JavaScript <code>throw</code> 机制立即生成并抛出错误。
这些是使用 JavaScript 语言提供的 <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" rel="nofollow"><code>try…catch</code> 构造</a>处理的。</p><pre class=""><code class="language-js"><span class="hljs-comment">// 由于 z 未定义，因此抛出 ReferenceError。</span>
<span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> m = <span class="hljs-number">1</span>;
  <span class="hljs-keyword">const</span> n = m + z;
} <span class="hljs-keyword">catch</span> (err) {
  <span class="hljs-comment">// 在此处理错误。</span>
}</code></pre><p class="">任何使用 JavaScript <code>throw</code> 机制都会引发异常，必须使用 <code>try…catch</code> 处理，否则 Node.js 进程将立即退出。</p><p class="">除了少数例外，同步的 API（任何不接受 <code>callback</code> 函数的阻塞方法，例如 <a href="../fs.html#fsreadfilesyncpath-options"><code>fs.readFileSync</code></a>）都使用 <code>throw</code> 来报告错误。</p><p class="">异步的 API 中发生的错误可以以多种方式报告：</p><ul class="">
<li>
<p>大多数接受 <code>callback</code> 函数的异步方法将接受作为第一个参数传给该函数的 <code>Error</code> 对象。
如果第一个参数不是 <code>null</code> 并且是 <code>Error</code> 的实例，则发生了应该处理的错误。</p>
<!-- eslint-disable no-useless-return -->
<pre><code class="language-js"><span class="hljs-keyword">const</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">'fs'</span>);
fs.<span class="hljs-title function_">readFile</span>(<span class="hljs-string">'a file that does not exist'</span>, <span class="hljs-function">(<span class="hljs-params">err, data</span>) =&gt;</span> {
  <span class="hljs-keyword">if</span> (err) {
    <span class="hljs-variable language_">console</span>.<span class="hljs-title function_">error</span>(<span class="hljs-string">'There was an error reading the file!'</span>, err);
    <span class="hljs-keyword">return</span>;
  }
  <span class="hljs-comment">// 否则处理数据</span>
});</code></pre>
</li>
<li>
<p>当在 <a href="../events.html#class-eventemitter"><code>EventEmitter</code></a> 对象上调用异步方法时，错误可以路由到该对象的 <code>'error'</code> 事件。</p>
<pre><code class="language-js"><span class="hljs-keyword">const</span> net = <span class="hljs-built_in">require</span>(<span class="hljs-string">'net'</span>);
<span class="hljs-keyword">const</span> connection = net.<span class="hljs-title function_">connect</span>(<span class="hljs-string">'localhost'</span>);

<span class="hljs-comment">// 向流中添加 'error' 事件句柄：</span>
connection.<span class="hljs-title function_">on</span>(<span class="hljs-string">'error'</span>, <span class="hljs-function">(<span class="hljs-params">err</span>) =&gt;</span> {
  <span class="hljs-comment">// 如果连接被服务器重置，</span>
  <span class="hljs-comment">// 或者根本无法连接，或者连接遇到任何类型的错误，</span>
  <span class="hljs-comment">// 则错误将发送到这里。</span>
  <span class="hljs-variable language_">console</span>.<span class="hljs-title function_">error</span>(err);
});

connection.<span class="hljs-title function_">pipe</span>(process.<span class="hljs-property">stdout</span>);</code></pre>
</li>
<li>
<p>Node.js API 中的一些典型的异步方法可能仍然使用 <code>throw</code> 机制来引发必须使用 <code>try…catch</code> 处理的异常。
没有此类方法的完整列表；请参阅每种方法的文档以确定所需的适当错误处理机制。</p>
</li>
</ul><p class=""><code>'error'</code> 事件机制的使用最常见于<a href="../stream.html">基于流</a>和<a href="../events.html#class-eventemitter">基于事件触发器</a>的 API，其本身代表了一系列随时间推移的异步操作（而不是单个操作可能通过或失败）。</p><p class="">对于所有的 <a href="../events.html#class-eventemitter"><code>EventEmitter</code></a> 对象，如果未提供 <code>'error'</code> 事件句柄，则将抛出错误，导致 Node.js 进程报告未捕获的异常并崩溃，除非：<a href="../domain.html"><code>domain</code></a> 模块使用得当或已为 <a href="../process.html#event-uncaughtexception"><code>'uncaughtException'</code></a> 事件注册句柄。</p><pre class=""><code class="language-js"><span class="hljs-keyword">const</span> <span class="hljs-title class_">EventEmitter</span> = <span class="hljs-built_in">require</span>(<span class="hljs-string">'events'</span>);
<span class="hljs-keyword">const</span> ee = <span class="hljs-keyword">new</span> <span class="hljs-title class_">EventEmitter</span>();

<span class="hljs-title function_">setImmediate</span>(<span class="hljs-function">() =&gt;</span> {
  <span class="hljs-comment">// 这将导致进程崩溃，</span>
  <span class="hljs-comment">// 因为没有添加 'error' 事件句柄。</span>
  ee.<span class="hljs-title function_">emit</span>(<span class="hljs-string">'error'</span>, <span class="hljs-keyword">new</span> <span class="hljs-title class_">Error</span>(<span class="hljs-string">'This will crash'</span>));
});</code></pre><p class="">以这种方式产生的错误不能使用 <code>try…catch</code> 拦截，因为其抛出后调用代码已经退出。</p><p class="">开发者必须参考每种方法的文档，以确定这些方法引发的错误是如何传播的。</p></div>
          <div id="content_right"><p>Node.js supports several mechanisms for propagating and handling errors that
occur while an application is running. How these errors are reported and
handled depends entirely on the type of <code>Error</code> and the style of the API that is
called.</p><p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate
and throw an error using the standard JavaScript <code>throw</code> mechanism. These
are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" rel="nofollow"><code>try…catch</code> construct</a> provided by the
JavaScript language.</p><pre><code class="language-js"><span class="hljs-comment">// Throws with a ReferenceError because z is not defined.</span>
<span class="hljs-keyword">try</span> {
  <span class="hljs-keyword">const</span> m = <span class="hljs-number">1</span>;
  <span class="hljs-keyword">const</span> n = m + z;
} <span class="hljs-keyword">catch</span> (err) {
  <span class="hljs-comment">// Handle the error here.</span>
}</code></pre><p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that
<em>must</em> be handled using <code>try…catch</code> or the Node.js process will exit
immediately.</p><p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not
accept a <code>callback</code> function, such as <a href="../fs.html#fsreadfilesyncpath-options"><code>fs.readFileSync</code></a>), will use <code>throw</code>
to report errors.</p><p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p><ul>
<li>
<p>Most asynchronous methods that accept a <code>callback</code> function will accept an
<code>Error</code> object passed as the first argument to that function. If that first
argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred
that should be handled.</p>
<!-- eslint-disable no-useless-return -->
<pre><code class="language-js"><span class="hljs-keyword">const</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">'fs'</span>);
fs.<span class="hljs-title function_">readFile</span>(<span class="hljs-string">'a file that does not exist'</span>, <span class="hljs-function">(<span class="hljs-params">err, data</span>) =&gt;</span> {
  <span class="hljs-keyword">if</span> (err) {
    <span class="hljs-variable language_">console</span>.<span class="hljs-title function_">error</span>(<span class="hljs-string">'There was an error reading the file!'</span>, err);
    <span class="hljs-keyword">return</span>;
  }
  <span class="hljs-comment">// Otherwise handle the data</span>
});</code></pre>
</li>
<li>
<p>When an asynchronous method is called on an object that is an
<a href="../events.html#class-eventemitter"><code>EventEmitter</code></a>, errors can be routed to that object's <code>'error'</code> event.</p>
<pre><code class="language-js"><span class="hljs-keyword">const</span> net = <span class="hljs-built_in">require</span>(<span class="hljs-string">'net'</span>);
<span class="hljs-keyword">const</span> connection = net.<span class="hljs-title function_">connect</span>(<span class="hljs-string">'localhost'</span>);

<span class="hljs-comment">// Adding an 'error' event handler to a stream:</span>
connection.<span class="hljs-title function_">on</span>(<span class="hljs-string">'error'</span>, <span class="hljs-function">(<span class="hljs-params">err</span>) =&gt;</span> {
  <span class="hljs-comment">// If the connection is reset by the server, or if it can't</span>
  <span class="hljs-comment">// connect at all, or on any sort of error encountered by</span>
  <span class="hljs-comment">// the connection, the error will be sent here.</span>
  <span class="hljs-variable language_">console</span>.<span class="hljs-title function_">error</span>(err);
});

connection.<span class="hljs-title function_">pipe</span>(process.<span class="hljs-property">stdout</span>);</code></pre>
</li>
<li>
<p>A handful of typically asynchronous methods in the Node.js API may still
use the <code>throw</code> mechanism to raise exceptions that must be handled using
<code>try…catch</code>. There is no comprehensive list of such methods; please
refer to the documentation of each method to determine the appropriate
error handling mechanism required.</p>
</li>
</ul><p>The use of the <code>'error'</code> event mechanism is most common for <a href="../stream.html">stream-based</a>
and <a href="../events.html#class-eventemitter">event emitter-based</a> APIs, which themselves represent a series of
asynchronous operations over time (as opposed to a single operation that may
pass or fail).</p><p>For <em>all</em> <a href="../events.html#class-eventemitter"><code>EventEmitter</code></a> objects, if an <code>'error'</code> event handler is not
provided, the error will be thrown, causing the Node.js process to report an
uncaught exception and crash unless either: The <a href="../domain.html"><code>domain</code></a> module is
used appropriately or a handler has been registered for the
<a href="../process.html#event-uncaughtexception"><code>'uncaughtException'</code></a> event.</p><pre><code class="language-js"><span class="hljs-keyword">const</span> <span class="hljs-title class_">EventEmitter</span> = <span class="hljs-built_in">require</span>(<span class="hljs-string">'events'</span>);
<span class="hljs-keyword">const</span> ee = <span class="hljs-keyword">new</span> <span class="hljs-title class_">EventEmitter</span>();

<span class="hljs-title function_">setImmediate</span>(<span class="hljs-function">() =&gt;</span> {
  <span class="hljs-comment">// This will crash the process because no 'error' event</span>
  <span class="hljs-comment">// handler has been added.</span>
  ee.<span class="hljs-title function_">emit</span>(<span class="hljs-string">'error'</span>, <span class="hljs-keyword">new</span> <span class="hljs-title class_">Error</span>(<span class="hljs-string">'This will crash'</span>));
});</code></pre><p>Errors generated in this way <em>cannot</em> be intercepted using <code>try…catch</code> as
they are thrown <em>after</em> the calling code has already exited.</p><p>Developers must refer to the documentation for each method to determine
exactly how errors raised by those methods are propagated.</p></div>
          <div></div>
        </div>

        <!-- <div id="biz_item" class="biz_wrap" data-biz="api_item">
          <a target="_blank" class="biz_link">
            <img class="biz_img" />
          </a>
        </div> -->
      </div>
    </div>
  </div>
  
  <div id="wxpaycode_box" style="display: none;">
    <div id="wxpaycode_img_box">
      <div id="wxpaycode_vip_tips">
        因经营维护成本巨大，
        <br>为了能提供更高质量的中文文档，
        <br>即日起将只对VIP会员开放。
        <br>扫码成为VIP会员，会员费用为<span id="wxpaycode_vip_money">199</span>元/年
      </div>
      <img id="wxpaycode_img">
    </div>
  </div>
  
  
  



    <script src="../../api/static/inject.js" defer=""></script></body></html>